# backup-job.yml
version: "3.7"
services:
  upload-site1:
    image: rakacha/lifi-grdrive-sync:1.0.0
    environment:
      - SYNC_MODE=UPLOAD
      - BACKUP_DIR=/home/frappe/frappe-bench/sites/${BACKUP_SITE_NAME}/private/backups
      - GDRIVE_DIR=${BACKUP_GDRIVE_PATH}
    volumes:
      - "sites-vol:/home/frappe/frappe-bench/sites"
      - "app-vol:/app"
    networks:
      - erpnext-network
      

networks:
  erpnext-network:
    external: true
    name: frappe_docker_default

volumes:
  sites-vol:
    external: true
    name: frappe_docker_sites
  app-vol:
    external: true
    name: gdrive-job-vol
